<a href="https://colab.research.google.com/github/Arushi0302/InClass-Prediction-Competition-She-Hacks-/blob/main/Model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as mtp  
import pandas as pd  
from sklearn.metrics import mean_squared_error
from math import sqrt

# Standard ML Models for comparison
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import ElasticNet
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import ExtraTreesRegressor
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.svm import SVR

# Splitting data into training/testing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler

# Metrics
from sklearn.metrics import mean_squared_error, mean_absolute_error, median_absolute_error

# Distributions
import scipy

In [ ]:
data_set= pd.read_csv('/content/wells_fargo_train.csv')  

In [ ]:
data_set.head()

Id Fiscal Year  Term Type  ...    Visa Status  Gender Unique Headcount
0   0     2008/09  Fall term  ...       Canadian    Male                5
1   1     2008/09  Fall term  ...       Canadian  Female                7
2   2     2008/09  Fall term  ...  International  Female                1
3   3     2008/09  Fall term  ...       Canadian    Male                3
4   4     2008/09  Fall term  ...       Canadian  Female               11

[5 rows x 15 columns]

In [ ]:
data_set.tail()

Id  Fiscal Year  Term Type  ...  Visa Status  Gender  Unique Headcount
24538  24538            2          1  ...            2       0                 1
24539  24539            2          1  ...            0       1                72
24540  24540            2          1  ...            0       0                 4
24541  24541            2          1  ...            1       1                15
24542  24542            2          1  ...            2       1                 4

[5 rows x 15 columns]

In [ ]:

x.shape

(24543, 14)

In [ ]:

# Import label encoder 
from sklearn import preprocessing 
  
# label_encoder object knows how to understand word labels. 
label_encoder = preprocessing.LabelEncoder() 
  
# Encode labels in column 'species'. 
data_set['Gender']= label_encoder.fit_transform(data_set['Gender'])  
data_set['Gender'].unique() 

data_set['Visa Status']= label_encoder.fit_transform(data_set['Visa Status'])  
data_set['Visa Status'].unique() 

data_set['Attendance']= label_encoder.fit_transform(data_set['Attendance'])  
data_set['Attendance'].unique() 

data_set['WorkTerm']= label_encoder.fit_transform(data_set['WorkTerm'])  
data_set['WorkTerm'].unique() 

data_set['Coop Regular']= label_encoder.fit_transform(data_set['Coop Regular'])  
data_set['Coop Regular'].unique() 

data_set['Program Grouping']= label_encoder.fit_transform(data_set['Program Grouping'])  
data_set['Program Grouping'].unique() 

data_set['Faculty Group']= label_encoder.fit_transform(data_set['Faculty Group'])  
data_set['Faculty Group'].unique() 

data_set['Study Year']= label_encoder.fit_transform(data_set['Study Year'])  
data_set['Study Year'].unique() 

data_set['Program Level']= label_encoder.fit_transform(data_set['Program Level'])  
data_set['Program Level'].unique() 

data_set['Career']= label_encoder.fit_transform(data_set['Career'])  
data_set['Career'].unique() 

data_set['Term Type']= label_encoder.fit_transform(data_set['Term Type'])  
data_set['Term Type'].unique() 

data_set['Fiscal Year']= label_encoder.fit_transform(data_set['Fiscal Year'])  
data_set['Fiscal Year'].unique() 

array([0, 1, 2])

In [ ]:
x= data_set.iloc[:, :-1].values  
y= data_set.iloc[:,-1].values  

In [ ]:
x.shape

(24543, 14)

In [ ]:
# Splitting the dataset into training and test set.  
from sklearn.model_selection import train_test_split  
x_train, x_test, y_train, y_test= train_test_split(x, y, test_size= 0.25, random_state=0)  

In [ ]:
x_test.shape

(6136, 14)

# **Decision Tree Classifier - GINI**

In [ ]:
#Fitting Decision Tree classifier to the training set  
from sklearn.tree import DecisionTreeClassifier  
classifier= DecisionTreeClassifier(criterion='gini', random_state=2,min_samples_leaf=7,max_features=0.5)  
classifier.fit(x_train, y_train)  

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=0.5, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=7, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=2, splitter='best')

In [ ]:
y_pred_dt= classifier.predict(x_test)  

In [ ]:

rms1 = sqrt(mean_squared_error(y_test, y_pred_dt))
rms1

14.450202219975148

# **SVM**

In [ ]:
from sklearn.svm import SVC
svclassifier = SVC(kernel='linear')
svclassifier.fit(x_train, y_train)

In [ ]:
y_pred_sv= svclassifier.predict(x_test)  

In [ ]:
rms5 = sqrt(mean_squared_error(y_test, y_pred_sv))
rms5

# **Naive Bayes**

In [ ]:
from sklearn.naive_bayes import GaussianNB
classifiern= GaussianNB() 
classifiern.fit(x_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [ ]:
y_pred_nb= classifiern.predict(x_test)  

In [ ]:
rms4 = sqrt(mean_squared_error(y_test, y_pred_nb))
rms4

27.287968560263582

# **Random Forest**

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_classification
clf = RandomForestClassifier(n_estimators=200, min_samples_leaf=3, 
                      max_features=0.5, n_jobs=-1, oob_score=True)
clf.fit(x_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features=0.5,
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=3, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=200,
                       n_jobs=-1, oob_score=True, random_state=None, verbose=0,
                       warm_start=False)

In [ ]:
y_pred_rf= clf.predict(x_test) 

In [ ]:

rms2 = sqrt(mean_squared_error(y_test, y_pred_rf))
rms2

13.541999711747138

In [ ]:
from sklearn.ensemble import RandomForestRegressor
m = RandomForestRegressor(n_estimators=100, min_samples_leaf=3, 
                      max_features=0.5, n_jobs=-1, oob_score=True)
m.fit(x_train, y_train)

RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=None, max_features=0.5, max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=3,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=100, n_jobs=-1, oob_score=True,
                      random_state=None, verbose=0, warm_start=False)

In [ ]:
y_pred_rfr= m.predict(x_test)

In [ ]:
rms7 = sqrt(mean_squared_error(y_test, y_pred_rfr))
rms7

9.487396802911636

# **Logistic Regression**

In [ ]:
from sklearn.linear_model import LogisticRegression
clfl = LogisticRegression(random_state=0)
clfl.fit(x_train, y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=0, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [ ]:
y_pred_lr= clfl.predict(x_test) 

In [ ]:
rms3 = sqrt(mean_squared_error(y_test, y_pred_lr))
rms3

18.693262899736784

# **Analysis**

In [ ]:
# Calculate mae and rmse
def evaluate_predictions(predictions, true):
    mae = np.mean(abs(predictions - true))
    rmse = np.sqrt(np.mean((predictions - true) ** 2))

    return mae, rmse

In [ ]:
def evaluate(X_train, X_test, y_train, y_test):
    # Names of models
    model_name_list = ['Linear Regression', 'ElasticNet Regression',
                      'Random Forest', 'Extra Trees', 'SVM',
                       'Gradient Boosted', 'Baseline']
    
    # Instantiate the models
    model1 = LinearRegression()
    model2 = ElasticNet(alpha=1.0, l1_ratio=0.5)
    model3 = RandomForestRegressor(n_estimators=100)
    model4 = ExtraTreesRegressor(n_estimators=100)
    model5 = SVR(kernel='rbf', degree=3, C=1.0, gamma='auto')
    model6 = GradientBoostingRegressor(n_estimators=50)
    
    # Dataframe for results
    results = pd.DataFrame(columns=['mae', 'rmse'], index = model_name_list)
    
    # Train and predict with each model
    for i, model in enumerate([model1, model2, model3, model4, model5, model6]):
        model.fit(X_train, y_train)
        predictions = model.predict(X_test)
        
        # Metrics
        mae = np.mean(abs(predictions - y_test))
        rmse = np.sqrt(np.mean((predictions - y_test) ** 2))
        
        # Insert results into the dataframe
        model_name = model_name_list[i]
        results.loc[model_name, :] = [mae, rmse]
    
    # Median Value Baseline Metrics
    baseline = np.median(y_train)
    baseline_mae = np.mean(abs(baseline - y_test))
    baseline_rmse = np.sqrt(np.mean((baseline - y_test) ** 2))
    
    results.loc['Baseline', :] = [baseline_mae, baseline_rmse]
    
    return results

In [ ]:
results = evaluate(x_train, x_test, y_train, y_test)
results

mae     rmse
Linear Regression      8.33177  15.5097
ElasticNet Regression  8.48391  15.9695
Random Forest          3.53645  8.73639
Extra Trees            3.27348  7.70091
SVM                    6.68859  16.9241
Gradient Boosted        7.1104  14.0186
Baseline               6.88168  17.4395

In [ ]:
model4 = ExtraTreesRegressor(n_estimators=90)
model4.fit(x_train, y_train)
y_pred_et= model4.predict(x_test)

In [ ]:
rms10 = sqrt(mean_squared_error(y_test, y_pred_et))
rms10

7.670822441763105

# **Testing**

In [ ]:
data_set1= pd.read_csv('/content/wells_fargo_test.csv')  

In [ ]:
from sklearn import preprocessing 
  
# label_encoder object knows how to understand word labels. 
label_encoder = preprocessing.LabelEncoder() 
  
# Encode labels in column 'species'. 
data_set1['Gender']= label_encoder.fit_transform(data_set1['Gender'])  
data_set1['Gender'].unique() 

data_set1['Visa Status']= label_encoder.fit_transform(data_set1['Visa Status'])  
data_set1['Visa Status'].unique() 

data_set1['Attendance']= label_encoder.fit_transform(data_set1['Attendance'])  
data_set1['Attendance'].unique() 

data_set1['WorkTerm']= label_encoder.fit_transform(data_set1['WorkTerm'])  
data_set1['WorkTerm'].unique() 

data_set1['Coop Regular']= label_encoder.fit_transform(data_set1['Coop Regular'])  
data_set1['Coop Regular'].unique() 

data_set1['Program Grouping']= label_encoder.fit_transform(data_set1['Program Grouping'])  
data_set1['Program Grouping'].unique() 

data_set1['Faculty Group']= label_encoder.fit_transform(data_set1['Faculty Group'])  
data_set1['Faculty Group'].unique() 

data_set1['Study Year']= label_encoder.fit_transform(data_set1['Study Year'])  
data_set1['Study Year'].unique() 

data_set1['Program Level']= label_encoder.fit_transform(data_set1['Program Level'])  
data_set1['Program Level'].unique() 

data_set1['Career']= label_encoder.fit_transform(data_set1['Career'])  
data_set1['Career'].unique() 

data_set1['Term Type']= label_encoder.fit_transform(data_set1['Term Type'])  
data_set1['Term Type'].unique() 

data_set1['Fiscal Year']= label_encoder.fit_transform(data_set1['Fiscal Year'])  
data_set1['Fiscal Year'].unique() 

array([0])

In [ ]:
xt= data_set1.iloc[:, :].values 

xt.shape

(10924, 14)

In [ ]:
x_test.shape

(6136, 14)

In [ ]:
y_pred_dtt= model4.predict(xt)  
for i in range(len(y_pred_dtt)):
  y_pred_dtt[i] =round( y_pred_dtt[i])
y_pred_dtt


array([4., 4., 2., ..., 1., 6., 6.])

In [ ]:
import csv
from itertools import zip_longest
list1 = xt[:,0]
list2 = y_pred_dtt
d = [list1, list2]
export_data = zip_longest(*d, fillvalue = '')
with open('sub91.csv', 'w', encoding="ISO-8859-1", newline='') as myfile:
      wr = csv.writer(myfile)
      wr.writerow(("Id", "Unique Headcount"))
      wr.writerows(export_data)
myfile.close()